
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://tczrmxklaylige:0df3692b7bb64e1abb219a2d94122b41947847767372c0b6ca664d7af8a5b03b@ec2-107-22-7-9.compute-1.amazonaws.com:5432/d4h3dq0eca9rli

test:
  <<: *default
  database: agunsaEcommerce_test


#
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
