
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agunsaEcommerce_development
  username: nicolas
  password: Meatlover3626

test:
  <<: *default
  database: agunsaEcommerce_test


#
production:
  <<: *default
  database: agunsaEcommerce_production
  username: agunsaEcommerce
  password: <%= ENV['AGUNSAECOMMERCE_DATABASE_PASSWORD'] %>
